export const appointmentConstants = {
    GET_AVALIABLE_DATES_REQUEST: 'APPOINTMENT_GET_AVALIABLE_DATES_REQUEST',
    GET_AVALIABLE_DATES_SUCCESS: 'APPOINTMENT_GET_AVALIABLE_DATES_SUCCESS',
    GET_AVALIABLE_DATES_FAILURE: 'APPOINTMENT_GET_AVALIABLE_DATES_FAILURE',
    CANCEL_REQUEST: 'APPOINTMENT_CANCEL_REQUEST',
    CANCEL_SUCCESS: 'APPOINTMENT_CANCEL_SUCCESS',
    CANCEL_FAILURE: 'APPOINTMENT_CANCEL_FAILURE',
};