export const authConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    SIGNIN_REQUEST: 'USERS_SIGNIN_REQUEST',
    SIGNIN_SUCCESS: 'USERS_SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'USERS_SIGNIN_FAILURE',

    GET_DATA_REQUEST: 'USERS_GET_DATA_REQUEST',
    GET_DATA_SUCCESS: 'USERS_GET_DATA_SUCCESS',
    GET_DATA_FAILURE: 'USERS_GET_DATA_FAILURE',

    SEND_MAIL_REQUEST: 'USERS_SEND_MAIL_REQUEST',
    SEND_MAIL_SUCCESS: 'USERS_SEND_MAIL_SUCCESS',
    SEND_MAIL_FAILURE: 'USERS_SEND_MAIL_FAILURE',

    CHANGE_PASSWORD_REQUEST: 'USERS_CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'USERS_CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'USERS_CHANGE_PASSWORD_FAILURE',

    LOGOUT: 'USERS_LOGOUT'
};