export const databasesConstants = {
    CLEAR_STATE: 'DB_CLEAR_STATE',
    BACKUP_REQUEST: 'DB_BACKUP_REQUEST',
    BACKUP_SUCCESS: 'DB_BACKUP_SUCCESS',
    BACKUP_FAILURE: 'DB_BACKUP_FAILURE',
    RESTORE_REQUEST: 'DB_RESTORE_REQUEST',
    RESTORE_SUCCESS: 'DB_RESTORE_SUCCESS',
    RESTORE_FAILURE: 'DB_RESTORE_FAILURE',
};