export const genericActionConstants = {
  GET_ALL_REQUEST: 'GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'GET_ALL_FAILURE',

  GET_ONE_REQUEST: 'GET_ONE_REQUEST',
  GET_ONE_SUCCESS: 'GET_ONE_SUCCESS',
  GET_ONE_FAILURE: 'GET_ONE_FAILURE',

  CREATE_REQUEST: 'CREATE_ONE_REQUEST',
  CREATE_SUCCESS: 'CREATE_ONE_SUCCESS',
  CREATE_FAILURE: 'CREATE_ONE_FAILURE',

  UPDATE_REQUEST: 'UPDATE_ONE_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_ONE_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_ONE_FAILURE',

  TOGGLE_ACTIVE_REQUEST: 'TOGGLE_ACTIVE_REQUEST',
  TOGGLE_ACTIVE_SUCCESS: 'TOGGLE_ACTIVE_SUCCESS',
  TOGGLE_ACTIVE_FAILURE: 'TOGGLE_ACTIVE_FAILURE',

  DELETE_ONE_REQUEST: 'DELETE_ONE_REQUEST',
  DELETE_ONE_SUCCESS: 'DELETE_ONE_SUCCESS',
  DELETE_ONE_FAILURE: 'DELETE_ONE_FAILURE',
}
