export const userConstants = {
    GET_ALL_REQUEST: 'USERS_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'USERS_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'USERS_GET_ALL_FAILURE',

    GET_ONE_REQUEST: 'USERS_GET_ONE_REQUEST',
    GET_ONE_SUCCESS: 'USERS_GET_ONE_SUCCESS',
    GET_ONE_FAILURE: 'USERS_GET_ONE_FAILURE',

    UPDATE_REQUEST: 'UPDATEET_ONE_REQUEST',
    UPDATE_SUCCESS: 'UPDATEET_ONE_SUCCESS',
    UPDATE_FAILURE: 'UPDATEET_ONE_FAILURE',

    TOGGLE_ACTIVE_REQUEST: 'USERS_TOGGLE_ACTIVE_REQUEST',
    TOGGLE_ACTIVE_SUCCESS: 'USERS_TOGGLE_ACTIVE_SUCCESS',
    TOGGLE_ACTIVE_FAILURE: 'USERS_TOGGLE_ACTIVE_FAILURE',
};